# -*- coding: utf-8 -*-
"""supermarket store_DA_Batch1.ipynbg

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wToBA97_8Pr_553dkiTThDHT9Ua0yVTI
"""

'''
supermarket store_DA_Batch1
group member
nisren hassanen mohamed
Eid Ahmed Abo Baid
zayed hemaid
dataset column:
Invoice id: Computer generated sales slip invoice identification number
Branch: Branch of supercenter (3 branches are available identified by A, B and C).
City: Location of supercenters
Customer type: Type of customers, recorded by Members for customers using member card and Normal for without member card.
Gender: Gender type of customer
Product line: General item categorization groups - Electronic accessories, Fashion accessories, Food and beverages, Health and beauty, Home and lifestyle, Sports and travel
Unit price: Price of each product in $
Quantity: Number of products purchased by customer
Tax: 5% tax fee for customer buying
Total: Total price including tax
Date: Date of purchase (Record available from January 2019 to March 2019)
Time: Purchase time (10am to 9pm)
Payment: Payment used by customer for purchase (3 methods are available – Cash, Credit card and Ewallet)
COGS: Cost of goods sold
Gross margin percentage: Gross margin percentage
Gross income: Gross income
Rating: Customer stratification rating on their overall shopping experience (On a scale of 1 to 10)
'''

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px

data = pd.read_csv('/content/supermarket_sales - Sheet1 (1).csv')

data.head(5)

data.info()

data.shape

data.notnull().sum()

data.describe()

#check for null values
data.isnull().sum()

sns.heatmap(data.isnull())

data.duplicated().sum()

data.duplicated()

data.nunique()

data['Branch'].value_counts().to_frame()

plt.figure(figsize=(20,8))
sns.countplot(data=data,x='Branch')
plt.title('Count of each Branch')

plt.show()

data['City'].value_counts().to_frame()

plt.figure(figsize=(20,8))
sns.countplot(data=data,x='City')
plt.title('Count of each City')

plt.show()

data['Customer type'].value_counts().to_frame()

plt.figure(figsize=(20,8))
sns.countplot(data=data,x='Customer type')
plt.title('Count of each Customer type')

plt.show()

data['Gender'].value_counts().to_frame()

plt.figure(figsize=(20,8))
sns.countplot(data=data,x='Gender')
plt.title('Count of each Gender')

plt.show()

data['Product line'].value_counts().to_frame()

plt.figure(figsize=(20,8))
sns.countplot(data=data,x='Product line')
plt.title('Count of each Product line')

plt.show()

data['Payment'].value_counts().to_frame()

plt.style.use('dark_background')
plt.figure(figsize=(20,8))
sns.countplot(data=data,x='Payment')
plt.title('Count of each Payment')

plt.show()

sns.lineplot(data=data,x ='Branch', y = 'gross margin percentage')

"""There is no changing in gross margin percentage so we can drop this column """

data = data.drop('gross margin percentage' , axis =1)
data.info()

"""convert data type from object to datetime"""

data['Time'] = pd.to_datetime(data['Time'])
data['Date'] = pd.to_datetime(data['Date'])

data.info()

"""Prodcut line has the highest sum of total sales in each City"""

m=data.groupby(['City' , 'Product line'])['Total'].sum()#In city Naypyitaw customers spend on Food and Beverages the most of Home and lifestyle 
m

"""# Naypyitaw Food and beverages max

"""

m.max()

"""Gender has the highest total sales  in each City"""

data.groupby(['Gender' , 'City'])['Total'].sum()#female paid more than Males in naypyitaw in other city male and female around the same

"""Average Sales for each Branch

"""

data.groupby('Branch')['Total'].mean()#branch c has the highest average sales

data.groupby('Gender')['Total'].sum()#Female paid more than men

data[['Quantity']].groupby(data['Product line']).sum().sort_values(by='Quantity',ascending=False)

pd.pivot_table(data,index='City',columns='Gender',aggfunc='count')

"""the 10 largest invoice by quantity"""

data.nlargest(10,'Quantity').loc[:,'Invoice ID']

"""the most payment method used by customers"""

data['Quantity'].groupby(data['Payment']).count()#Cash and Ewallet the most common payment ways while Credit Card are less common

"""The average gross income by city"""

data.groupby('City')['gross income'].mean()#max Naypyitaw min Yangon

"""the average of rating for every product due to gender"""

pd.pivot_table(data,index='Gender',columns='Product line',values='Rating',aggfunc='mean')

data.groupby('Product line')['Rating'].mean()#max rate Food and beverages,min rate Home and lifestyle

"""the most product that females buy but only (females members)

"""

d=data[(data['Gender']=='Female')&(data['Customer type']=='Member')]
d['Quantity'].groupby(data['Product line']).count()

s=data[(data['Gender']=='Female')&(data['Customer type']=='Normal')]
s['Quantity'].groupby(data['Product line']).count()

data.loc[data.groupby("Gender")["Quantity"].idxmax()]

data['Quantity'].max()

"""Average Sales for Product Lines"""

s1=data.groupby('Product line')['Total'].mean()# max Home and lifestyle      
s1

plt.style.use('dark_background')
plt.figure(figsize=(20,5))
plt.plot(s1.index,s1.values,linestyle='dashdot',color='red',linewidth=3
         ,marker='o',ms=20,mec='red',mfc='white')

plt.xlabel('products',color='green',size=22,family='serif')
plt.ylabel('Total')
plt.grid(axis='y',color='red',linewidth=2,linestyle='dotted')
plt.grid(axis='x',color='white',linewidth=2,linestyle='dotted')
plt.show()

data.describe()

d=data['Total'].groupby(data['Product line']).sum()
s=data['Quantity'].groupby(data['Product line']).sum()

d

plt.style.use('dark_background')
plt.figure(figsize=(20,5))
plt.plot(d.index,d.values,linestyle='dashdot',color='red',linewidth=3
         ,marker='o',ms=20,mec='red',mfc='white')

plt.xlabel('products',color='green',size=22,family='serif')
plt.ylabel('Total')
plt.grid(axis='y',color='red',linewidth=2,linestyle='dotted')
plt.grid(axis='x',color='white',linewidth=2,linestyle='dotted')
plt.show()

"""how many males and females in each city"""

import seaborn as sns
plt.figure(figsize=(20,5))
sns.countplot(data=data,x='City',hue='Gender',palette='CMRmap')

import seaborn as sns
plt.figure(figsize=(20,5))
sns.countplot(data=data,x='Product line',hue='Gender',palette='CMRmap')#Females are interested in Fashion accessories Males are interested in Health and Beauty

plt.style.use('default')
plt.figure(figsize=(20,5))
sns.countplot(data=data,x='Product line',hue='Customer type',palette =  'rocket_r')#Member Customers prefer buy Food and beverages , Sports and Travel ,Normal Customers prefer buy electronic and fashion accessories

plt.figure(figsize=(20,5))
sns.boxplot(data=data,x='Product line',y='Quantity',width=0.5,hue='Customer type',showmeans=True,
           meanprops={'marker':'o','markerfacecolor':'r','markersize':10,'markeredgecolor':'white'},
           palette='CMRmap')

sns.catplot(data=data,x='Gender',y='Quantity',kind='box')

ad = sns.countplot(x = 'Gender' , hue= 'Payment' , data =data , palette = 'Accent_r')
plt.title('the most common payment way per Gender')#Males prefere pay with Ewallet Women prefere pay with Cash

#Most sales were in the city of Naypyitaw And on 1/23/2019
data.groupby(['Date','City'])['Total'].sum().sort_values(ascending=False)

data['Month'] = data['Date'].dt.month_name()

data.info()

data['Month']

data['number of month'] = data['Date'].dt.month

data['hour'] = data['Time'].dt.hour
data['hour']

data['hour'].describe()

data.info()

sortbymonth= data.groupby(['Month' , 'number of month'])['Quantity'].sum().reset_index(drop = False)
sort = sortbymonth.sort_values(by = 'number of month')
sort

sort.Month

import numpy as np 
plt.style.use('dark_background')
plt.figure(figsize=(20,5))
plt.plot(sort.Month,sort.Quantity,linestyle='dashdot',color='red',linewidth=3
         ,marker='o',ms=20,mec='red',mfc='white')
plt.xlabel('Month',color='green',size=22,family='serif')
plt.ylabel('Quantity')
plt.grid(axis='y',color='red',linewidth=2,linestyle='dotted')
plt.grid(axis='x',color='white',linewidth=2,linestyle='dotted')
plt.show()

sortbymonth= data.groupby(['Month' , 'number of month'])['Total'].sum().reset_index(drop = False)
sort1 = sortbymonth.sort_values(by = 'number of month')
sort1

import numpy as np 
plt.style.use('dark_background')
plt.figure(figsize=(20,5))
plt.plot(sort1.Month,sort1.Total,linestyle='dashdot',color='red',linewidth=3
         ,marker='o',ms=20,mec='red',mfc='white')
plt.xlabel('Month',color='green',size=22,family='serif')
plt.ylabel('Total')
plt.grid(axis='y',color='red',linewidth=2,linestyle='dotted')
plt.grid(axis='x',color='white',linewidth=2,linestyle='dotted')
plt.show()

sort2=data.groupby(['City','Month'])['Total'].sum().sort_values()
sort2# max sales in january and naypyitaw

#Most sales were in the city of Naypyitaw And on 1/23/2019
data.groupby(['City','Date'])['Total'].sum().sort_values(ascending=False)

data.groupby(['City'])['cogs'].sum().sort_values(ascending=False)

sns.lineplot(data=data,x ='City', y = 'cogs')

data.groupby(['Month'])['cogs'].sum().sort_values(ascending=False)

sort3bymonth= data.groupby(['Month' , 'number of month'])['cogs'].sum().reset_index(drop = False)
sort3 = sort3bymonth.sort_values(by = 'number of month')
sort3

import numpy as np 
plt.style.use('dark_background')
plt.figure(figsize=(20,5))
plt.plot(sort3.Month,sort3.cogs,linestyle='dashdot',color='red',linewidth=3
         ,marker='o',ms=20,mec='red',mfc='white')
plt.xlabel('Month',color='green',size=22,family='serif')
plt.ylabel('cogs')
plt.grid(axis='y',color='red',linewidth=2,linestyle='dotted')
plt.grid(axis='x',color='white',linewidth=2,linestyle='dotted')
plt.show()

sortbyhour=data.groupby(['City','hour'])['Total'].sum().sort_values(ascending=False)#max sales on 7 o'clock night
sortbyhour

import seaborn as sns
plt.figure(figsize=(20,5))
sns.countplot(data=data,x='City',hue='hour',palette='CMRmap')

data[['City','hour']].groupby(data['Total']).sum()

'''
<<< Conclusion >>>
supermarket have 3 Branch A,B,C in 3 city Naypyitaw,Yangon,Mandalay 
Customer type 2 type member,normal
Gender male and female
Product line 5 line Fashion accessories,Food and beverages,Electronic accessories,Sports and travel,Home and lifestyle,Health and beauty
Payment 3 ways  Ewallet,Cash,Credit card
Food and Beverages the highest product line in city Naypyitaw and minimum Home and lifestyle
female paid more than Males in naypyitaw 
branch c has the highest average sales
Cash and Ewallet the most common payment ways while Credit Card are less common
The highest Gross income in naypyitaw
max rate Food and beverages,min rate Home and lifestyle
Females are interested in Fashion accessories Males are interested in Health and Beauty 
Member Customers prefer buy Food and beverages , Sports and Travel ,  Normal Customers prefer buy electronic and fashion accessories
Males prefere pay with Ewallet Women prefere pay with Cash
Most sales were in the city of Naypyitaw And on 1/23/2019
The highest sales in month January and city Naypyitaw
In January sold the highest quantity then March then February
The highest cost of good sold in city Naypyitaw and January and 
February the minimum month

'''